// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1tNTHrdloslI9juvufTMKzCRRwCOEHAI',
    appId: '1:226250293712:web:2854f8d6769cf93ceab9d5',
    messagingSenderId: '226250293712',
    projectId: 'aichatvoiceapp',
    authDomain: 'aichatvoiceapp.firebaseapp.com',
    storageBucket: 'aichatvoiceapp.firebasestorage.app',
    measurementId: 'G-3GZ19CKC8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYpkJ7EYVMcwYVq9Wnqci88cjKb-yFW8',
    appId: '1:226250293712:android:6f5da6c23ac3039feab9d5',
    messagingSenderId: '226250293712',
    projectId: 'aichatvoiceapp',
    storageBucket: 'aichatvoiceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwcQ6OE75MMFTSvYq47iEhhN9STnLn4DE',
    appId: '1:226250293712:ios:70bda93c5213c622eab9d5',
    messagingSenderId: '226250293712',
    projectId: 'aichatvoiceapp',
    storageBucket: 'aichatvoiceapp.firebasestorage.app',
    iosBundleId: 'com.example.aiVoiceChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwcQ6OE75MMFTSvYq47iEhhN9STnLn4DE',
    appId: '1:226250293712:ios:70bda93c5213c622eab9d5',
    messagingSenderId: '226250293712',
    projectId: 'aichatvoiceapp',
    storageBucket: 'aichatvoiceapp.firebasestorage.app',
    iosBundleId: 'com.example.aiVoiceChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1tNTHrdloslI9juvufTMKzCRRwCOEHAI',
    appId: '1:226250293712:web:5bc7a7607b324910eab9d5',
    messagingSenderId: '226250293712',
    projectId: 'aichatvoiceapp',
    authDomain: 'aichatvoiceapp.firebaseapp.com',
    storageBucket: 'aichatvoiceapp.firebasestorage.app',
    measurementId: 'G-RCYTMDZZ7J',
  );
}
